version: '3.7'

services:
  rentalx_db:
    image: postgres
    container_name: rentalx_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=rentalx
      - POSTGRES_PASSWORD=dbrentalx
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentalx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - rentalx_db
    depends_on:
      - rentalx_db

volumes:
  pgdata:
    driver: local
